# This should be an action instead of the .devcontainer setup? I think?
name: Build and Export Amulet Game

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip libgl1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libasound2-dev

    - name: Download Amulet
      run: |
        # wget https://www.amulet.xyz/latest/amulet.zip
        wget https://github.com/ianmaclarty/amulet/releases/download/v1.21.10/amulet-v1.21.10-linux.zip -O amulet.zip

    - name: Unzip and Repair Structure
      run: |
        unzip ./amulet.zip
        mkdir amulet
        cd amulet-v1.21.10
        mv * ../amulet
        cd ..
        rmdir amulet-v1.21.10
        rm amulet.zip
        chmod +x ./amulet/amulet.sh

    - name: Show Location
      run: |
        ls

    - name: Build and export game
      run: |
        ./amulet/amulet export "../main.lua" game.zip
